CREATE TABLE Client
(
  CID VARCHAR(20) NOT NULL,
  DisplayName VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  PRIMARY KEY (CID)
);

CREATE TABLE CGroup
(
  GID VARCHAR(20) NOT NULL,
  GName VARCHAR(255),
  PRIMARY KEY (GID)
);

CREATE TABLE ClientInGroup
(
  CID VARCHAR(20) NOT NULL,
  GID VARCHAR(20) NOT NULL,
  PRIMARY KEY (CID, GID),
  FOREIGN KEY (CID) REFERENCES Client(CID),
  FOREIGN KEY (GID) REFERENCES CGroup(GID)
);

CREATE TABLE Message
(
  MID VARCHAR(255) NOT NULL,
  Timestamp datetime NOT NULL,
  Text VARCHAR(255) NOT NULL,
  CID VARCHAR(20) NOT NULL,
  GID VARCHAR(20) NOT NULL,
  PRIMARY KEY (MID),
  FOREIGN KEY (CID) REFERENCES Client(CID),
  FOREIGN KEY (GID) REFERENCES CGroup(GID)
);

CREATE TABLE Break
(
  CID VARCHAR(20) NOT NULL,
  GID VARCHAR(20) NOT NULL,
  MID VARCHAR(255) NOT NULL,
  PRIMARY KEY (CID, GID),
  FOREIGN KEY (CID) REFERENCES Client(CID),
  FOREIGN KEY (GID) REFERENCES CGroup(GID),
  FOREIGN KEY (MID) REFERENCES Message(MID)
);

DELIMITER &&
CREATE DEFINER=`root`@`localhost` FUNCTION `getTime`() RETURNS datetime
BEGIN
	RETURN now();
END&&
DELIMITER ;
